- name: Setup iTerm2
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Install iTerm2 via Homebrew Cask
      homebrew_cask:
        name: iterm2
        state: present

    - name: Remove existing .oh-my-zsh directory
      file:
        path: "~/.oh-my-zsh"
        state: absent

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        executable: /bin/bash

    - name: Install Meslo Nerd Font
      homebrew_cask:
        name: font-meslo-lg-nerd-font
        state: present

    - name: Install Powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1

    - name: Remove existing zsh configuration files
      file:
        path: "~/{{ item }}"
        state: absent
      loop:
        - .zshrc
        - .zprofile
        - .zshenv

    - name: Copy new zsh configuration files from dotfiles
      copy:
        src: "{{ item.src }}"
        dest: "~/{{ item.dest }}"
        remote_src: true
      loop:
        - { src: "~/dotfiles/.zshrc", dest: ".zshrc" }
        - { src: "~/dotfiles/.zprofile", dest: ".zprofile" }
        - { src: "~/dotfiles/.zshenv", dest: ".zshenv" }
        - { src: "~/dotfiles/.profile", dest: ".profile" }
        - { src: "~/dotfiles/.p10k.zsh", dest: ".p10k.zsh" }

    - name: Clone zsh-autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        depth: 1

    - name: Clone zsh-syntax-highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        depth: 1

    - name: Copy iTerm2 theme file from dotfiles to Downloads
      copy:
        src: "~/dotfiles/rose-pine-moon.itermcolors"
        dest: "~/Downloads/rose-pine-moon.itermcolors"
        remote_src: true
